In [ ]:
import pandas as pd

df = pd.read_csv('C:/Users/Admin/Desktop/belarus_data.csv.csv') 
df.head(10)
df.tail(10)

                                      Year     1995 [YR1995]  \
0                                 GDP_Real       65011079700
1                                Inv_Share  24.7498002520531
2                       Labor force, total           4754039
3                               Pop_Growth          10193831
4                                 RD_Share                ..
5  Researchers in R&D (per million people)                ..
6                                Inflation  709.346032118606
7                             Export_Share  49.6651647817599
8                                     Rate               175

      1996 [YR1996]     1997 [YR1997]     1998 [YR1998]     1999 [YR1999]  \
0       66831392900       74450175300       80703983600       83447918400
1  23.5192009966691  26.8369544475643  26.7119649197264  23.7067689249137
2           4745323           4716116           4721707           4752493
3          10159569          10117433          10071963          10026738
4           0.99852              0.73           0.70578           0.84523
5                ..                ..                ..                ..
6  52.7120767531954  63.9373663357478  72.8697170535354  293.678750889773
7  46.3498037416792  59.8598805986424  59.0511292994057  59.2033413701759
8  62.3333333333333              31.8  26.9916666666667  51.0416666666667

      2000 [YR2000]     2001 [YR2001]     2002 [YR2002]     2003 [YR2003]  \
0       88287900400       92459773900       97124616900      103965290600
1  25.3986730605006  23.7608599445648  22.1768515932559  24.9543276593883
2           4815953           4871194           4907156           4931485
3           9979610           9928549           9865548           9796749
4            0.7221           0.70876            0.6209           0.61147
5                ..                ..                ..                ..
6  168.620235850934  61.1349331618476  42.5375481348794  28.3978399133474
7  69.2108213448948  66.7476067360771  63.6275159440361   65.156379906358
8  67.6666666666667  46.9666666666667  36.8833333333333            23.975

      2004 [YR2004]     2005 [YR2005]     2006 [YR2006]     2007 [YR2007]  \
0      115869049400      126760741800      139436809300      151428384100
1  28.6673014374357  28.4604661956657  32.1841371566982  34.0919031794272
2           4948132           4959928           4973237           4990775
3           9730146           9663915           9604924           9560953
4           0.62759           0.67852           0.66065           0.96203
5                ..                ..                ..                ..
6  18.1082424937646  10.3388794457932  6.99712903535585  8.42675273505309
7  67.8863333586708  59.7978087236099  60.0613117690842  60.9430527153212
8  16.9083333333333  11.3583333333333  8.84166666666667             8.575

      2008 [YR2008]     2009 [YR2009]     2010 [YR2010]     2011 [YR2011]  \
0      166874078500      167207818700      180166453200      190165645800
1  37.6416510261128  36.8640444559238  40.6563662623236  37.2175950788459
2           5018075           5048840           5073617           5090448
3           9527985           9504583           9483836           9461643
4           0.74147           0.62167           0.66913            0.6776
5                ..                ..                ..                ..
6  14.8378764828254  12.9456563410401    7.735748043125  53.2286983118174
7  60.9377552183976  48.8764618241933  51.3728853529564  78.4653615193087
8              8.55            11.675  9.21666666666667            13.575

      2012 [YR2012]     2013 [YR2013]     2014 [YR2014]     2015 [YR2015]  \
0      193413394600      195345051500      198570441900      190966046700
1  35.0942730563184  38.7980262073973  34.8410329356421  29.0346959914608
2           5096141           5097773           5098253           5097379
3           9446836           9443211           9448515           9461076
4           0.64603           0.65191           0.50548           0.49999
5                ..                ..                ..                ..
6  59.2197360232518  18.3122610377873  18.1195543526734  13.5344897649735
7  78.7769072783938  58.3335781066769   54.941004057247  58.0107665670743
8  19.4916666666667  19.1333333333333  18.7416666666667  18.0833333333333

      2016 [YR2016]     2017 [YR2017]     2018 [YR2018]     2019 [YR2019]  \
0      186141391800      190854833400      196865229200      199712797100
1  26.4775827022928  28.0303589091824  28.0788785453202  29.1499946931726
2           5092675           5079681           5054114           5025008
3           9469379           9458989           9438785           9419758
4           0.50063           0.58411           0.60443           0.57733
5                ..                ..                ..                ..
6  11.8365807653496  6.03183725177785   4.8723022055069  5.59815595039854
7  62.5093471231924  66.7896002012327  70.4550452625374  65.0945839929757
8              14.4  9.65871241633364  8.69583333333333  9.02333333333333

   2020 [YR2020]  2021 [YR2021]  2022 [YR2022]  2023 [YR2023]  \
0   1.983692e+11   2.032072e+11   1.937410e+11   2.017358e+11
1   2.745484e+01   2.438073e+01   2.159791e+01   2.471168e+01
2   4.982156e+06   4.938726e+06   4.907541e+06   4.861854e+06
3   9.379952e+06   9.302585e+06   9.228071e+06   9.178298e+06
4   5.390100e-01   4.598100e-01   4.747700e-01   5.784300e-01
5   1.473378e+03   1.439197e+03   1.434190e+03   1.504353e+03
6   5.548144e+00   9.460284e+00   1.520968e+01   5.000599e+00
7   6.101210e+01   7.083176e+01   6.305119e+01   6.602673e+01
8   9.032500e+00   1.011750e+01   1.271583e+01   9.962307e+00

      2024 [YR2024]
0      209825100000
1  25.8358517163125
2           4835456
3           9132629
4                ..
5                ..
6  5.78531910427999
7  65.0639450286877
8  9.99166666666667
                                      Year     1995 [YR1995]  \
0                                 GDP_Real       65011079700
1                                Inv_Share  24.7498002520531
2                       Labor force, total           4754039
3                               Pop_Growth          10193831
4                                 RD_Share                ..
5  Researchers in R&D (per million people)                ..
6                                Inflation  709.346032118606
7                             Export_Share  49.6651647817599
8                                     Rate               175

      1996 [YR1996]     1997 [YR1997]     1998 [YR1998]     1999 [YR1999]  \
0       66831392900       74450175300       80703983600       83447918400
1  23.5192009966691  26.8369544475643  26.7119649197264  23.7067689249137
2           4745323           4716116           4721707           4752493
3          10159569          10117433          10071963          10026738
4           0.99852              0.73           0.70578           0.84523
5                ..                ..                ..                ..
6  52.7120767531954  63.9373663357478  72.8697170535354  293.678750889773
7  46.3498037416792  59.8598805986424  59.0511292994057  59.2033413701759
8  62.3333333333333              31.8  26.9916666666667  51.0416666666667

      2000 [YR2000]     2001 [YR2001]     2002 [YR2002]     2003 [YR2003]  \
0       88287900400       92459773900       97124616900      103965290600
1  25.3986730605006  23.7608599445648  22.1768515932559  24.9543276593883
2           4815953           4871194           4907156           4931485
3           9979610           9928549           9865548           9796749
4            0.7221           0.70876            0.6209           0.61147
5                ..                ..                ..                ..
6  168.620235850934  61.1349331618476  42.5375481348794  28.3978399133474
7  69.2108213448948  66.7476067360771  63.6275159440361   65.156379906358
8  67.6666666666667  46.9666666666667  36.8833333333333            23.975

      2004 [YR2004]     2005 [YR2005]     2006 [YR2006]     2007 [YR2007]  \
0      115869049400      126760741800      139436809300      151428384100
1  28.6673014374357  28.4604661956657  32.1841371566982  34.0919031794272
2           4948132           4959928           4973237           4990775
3           9730146           9663915           9604924           9560953
4           0.62759           0.67852           0.66065           0.96203
5                ..                ..                ..                ..
6  18.1082424937646  10.3388794457932  6.99712903535585  8.42675273505309
7  67.8863333586708  59.7978087236099  60.0613117690842  60.9430527153212
8  16.9083333333333  11.3583333333333  8.84166666666667             8.575

      2008 [YR2008]     2009 [YR2009]     2010 [YR2010]     2011 [YR2011]  \
0      166874078500      167207818700      180166453200      190165645800
1  37.6416510261128  36.8640444559238  40.6563662623236  37.2175950788459
2           5018075           5048840           5073617           5090448
3           9527985           9504583           9483836           9461643
4           0.74147           0.62167           0.66913            0.6776
5                ..                ..                ..                ..
6  14.8378764828254  12.9456563410401    7.735748043125  53.2286983118174
7  60.9377552183976  48.8764618241933  51.3728853529564  78.4653615193087
8              8.55            11.675  9.21666666666667            13.575

      2012 [YR2012]     2013 [YR2013]     2014 [YR2014]     2015 [YR2015]  \
0      193413394600      195345051500      198570441900      190966046700
1  35.0942730563184  38.7980262073973  34.8410329356421  29.0346959914608
2           5096141           5097773           5098253           5097379
3           9446836           9443211           9448515           9461076
4           0.64603           0.65191           0.50548           0.49999
5                ..                ..                ..                ..
6  59.2197360232518  18.3122610377873  18.1195543526734  13.5344897649735
7  78.7769072783938  58.3335781066769   54.941004057247  58.0107665670743
8  19.4916666666667  19.1333333333333  18.7416666666667  18.0833333333333

      2016 [YR2016]     2017 [YR2017]     2018 [YR2018]     2019 [YR2019]  \
0      186141391800      190854833400      196865229200      199712797100
1  26.4775827022928  28.0303589091824  28.0788785453202  29.1499946931726
2           5092675           5079681           5054114           5025008
3           9469379           9458989           9438785           9419758
4           0.50063           0.58411           0.60443           0.57733
5                ..                ..                ..                ..
6  11.8365807653496  6.03183725177785   4.8723022055069  5.59815595039854
7  62.5093471231924  66.7896002012327  70.4550452625374  65.0945839929757
8              14.4  9.65871241633364  8.69583333333333  9.02333333333333

   2020 [YR2020]  2021 [YR2021]  2022 [YR2022]  2023 [YR2023]  \
0   1.983692e+11   2.032072e+11   1.937410e+11   2.017358e+11
1   2.745484e+01   2.438073e+01   2.159791e+01   2.471168e+01
2   4.982156e+06   4.938726e+06   4.907541e+06   4.861854e+06
3   9.379952e+06   9.302585e+06   9.228071e+06   9.178298e+06
4   5.390100e-01   4.598100e-01   4.747700e-01   5.784300e-01
5   1.473378e+03   1.439197e+03   1.434190e+03   1.504353e+03
6   5.548144e+00   9.460284e+00   1.520968e+01   5.000599e+00
7   6.101210e+01   7.083176e+01   6.305119e+01   6.602673e+01
8   9.032500e+00   1.011750e+01   1.271583e+01   9.962307e+00

      2024 [YR2024]
0      209825100000
1  25.8358517163125
2           4835456
3           9132629
4                ..
5                ..
6  5.78531910427999
7  65.0639450286877
8  9.99166666666667

In [13]:
# Снять ограничение на количество выводимых столбцов
pd.set_option('display.max_columns', None)

# Вывести датафрейм (теперь покажутся все колонки)
df.head(3)

,Year,1995 [YR1995],1996 [YR1996],1997 [YR1997],1998 [YR1998],1999 [YR1999],2000 [YR2000],2001 [YR2001],2002 [YR2002],2003 [YR2003],2004 [YR2004],2005 [YR2005],2006 [YR2006],2007 [YR2007],2008 [YR2008],2009 [YR2009],2010 [YR2010],2011 [YR2011],2012 [YR2012],2013 [YR2013],2014 [YR2014],2015 [YR2015],2016 [YR2016],2017 [YR2017],2018 [YR2018],2019 [YR2019],2020 [YR2020],2021 [YR2021],2022 [YR2022],2023 [YR2023],2024 [YR2024]
0,GDP_Real,65011079700,66831392900,74450175300,80703983600,83447918400,88287900400,92459773900,97124616900,103965290600,115869049400,126760741800,139436809300,151428384100,166874078500,167207818700,180166453200,190165645800,193413394600,195345051500,198570441900,190966046700,186141391800,190854833400,196865229200,199712797100,1.983692e+11,2.032072e+11,1.937410e+11,2.017358e+11,209825100000
1,Inv_Share,24.7498002520531,23.5192009966691,26.8369544475643,26.7119649197264,23.7067689249137,25.3986730605006,23.7608599445648,22.1768515932559,24.9543276593883,28.6673014374357,28.4604661956657,32.1841371566982,34.0919031794272,37.6416510261128,36.8640444559238,40.6563662623236,37.2175950788459,35.0942730563184,38.7980262073973,34.8410329356421,29.0346959914608,26.4775827022928,28.0303589091824,28.0788785453202,29.1499946931726,2.745484e+01,2.438073e+01,2.159791e+01,2.471168e+01,25.8358517163125
2,"Labor force, total",4754039,4745323,4716116,4721707,4752493,4815953,4871194,4907156,4931485,4948132,4959928,4973237,4990775,5018075,5048840,5073617,5090448,5096141,5097773,5098253,5097379,5092675,5079681,5054114,5025008,4.982156e+06,4.938726e+06,4.907541e+06,4.861854e+06,4835456

In [14]:
df.describe()

       2020 [YR2020]  2021 [YR2021]  2022 [YR2022]  2023 [YR2023]
count   9.000000e+00   9.000000e+00   9.000000e+00   9.000000e+00
mean    2.204262e+10   2.258016e+10   2.152835e+10   2.241665e+10
std     6.612248e+10   6.773514e+10   6.457974e+10   6.724468e+10
min     5.390100e-01   4.598100e-01   4.747700e-01   5.784300e-01
25%     9.032500e+00   1.011750e+01   1.520968e+01   9.962307e+00
50%     6.101210e+01   7.083176e+01   6.305119e+01   6.602673e+01
75%     4.982156e+06   4.938726e+06   4.907541e+06   4.861854e+06
max     1.983692e+11   2.032072e+11   1.937410e+11   2.017358e+11

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 9 entries, 0 to 8
Data columns (total 31 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Year           9 non-null      str
 1   1995 [YR1995]  9 non-null      str
 2   1996 [YR1996]  9 non-null      str
 3   1997 [YR1997]  9 non-null      str
 4   1998 [YR1998]  9 non-null      str
 5   1999 [YR1999]  9 non-null      str
 6   2000 [YR2000]  9 non-null      str
 7   2001 [YR2001]  9 non-null      str
 8   2002 [YR2002]  9 non-null      str
 9   2003 [YR2003]  9 non-null      str
 10  2004 [YR2004]  9 non-null      str
 11  2005 [YR2005]  9 non-null      str
 12  2006 [YR2006]  9 non-null      str
 13  2007 [YR2007]  9 non-null      str
 14  2008 [YR2008]  9 non-null      str
 15  2009 [YR2009]  9 non-null      str
 16  2010 [YR2010]  9 non-null      str
 17  2011 [YR2011]  9 non-null      str
 18  2012 [YR2012]  9 non-null      str
 19  2013 [YR2013]  9 non-null      str
 20  2014 [YR2014]  9 non-null      str
 21  2015 [YR2015]  9 non-null      str
 22  2016 [YR2016]  9 non-null      str
 23  2017 [YR2017]  9 non-null      str
 24  2018 [YR2018]  9 non-null      str
 25  2019 [YR2019]  9 non-null      str
 26  2020 [YR2020]  9 non-null      float64
 27  2021 [YR2021]  9 non-null      float64
 28  2022 [YR2022]  9 non-null      float64
 29  2023 [YR2023]  9 non-null      float64
 30  2024 [YR2024]  9 non-null      str
dtypes: float64(4), str(27)
memory usage: 2.3 KB