Датасет содержит данные по результатам голосвания на некоторых участках президентских выборов 2020 г. в Беларуси: регион, район, город, адрес участка, число избирателей, показатели явки и распределение голосов между кандидатами.
Цель - проверить качество данных, описать структуру распределений, подготовить признаки и сформулировать гипотезы для дальнейшего моделирования.

In [1]:
import pandas as pd
import numpy as np
import matplotlib as plt
import seaborn as sns
import plotly as px

In [2]:

df = pd.read_csv('Protocol_data.csv')
df.head()

,Region,District,City,Address,Polling station number,Polling station code,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,...,Dmitriev,Konopackaya,Lukashenko,Tsikhanouskaya,Cherechen,Against all,Number of ballots declared invalid,Number of ballots received by the precinct commission,Number of spoiled ballots,Number of unused ballots
0,Брестская,Брест - Ленинский,Брест,"ул. Гоголя, 7, УО «Брестский государственный м...",1,01-010-0001,1656.0,1329.0,1319,252.0,...,21.0,16,464,701,16.0,96.0,5.0,1660,1.0,330.0
1,Брестская,Брест - Ленинский,Брест,"ул. Героев обороны Брестской крепости, 78, УО ...",2,01-010-0002,2646.0,2249.0,2249,707.0,...,43.0,25,994,948,32.0,194.0,13.0,2670,0.0,421.0
2,Брестская,Брест - Ленинский,Брест,"ул. Пригородная, 25, УО «Брестское государстве...",4,01-010-0004,1805.0,1717.0,1714,537.0,...,32.0,26,1125,395,24.0,97.0,15.0,1880,0.0,163.0
3,Брестская,Брест - Ленинский,Брест,"ул. Смирнова, 21, общежитие ОАО «Брестский мяс...",5,01-010-0005,2270.0,2122.0,2122,863.0,...,42.0,21,1506,412,50.0,91.0,NaN,NaN,NaN,NaN
4,Брестская,Брест - Ленинский,Брест,"ул. Смирнова, 63, ГУО «Средняя школа № 5 г. Бр...",6,01-010-0006,2746.0,2383.0,2383,507.0,...,53.0,28,923,1157,48.0,174.0,NaN,NaN,NaN,NaN

In [3]:
df.tail()

,Region,District,City,Address,Polling station number,Polling station code,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,...,Dmitriev,Konopackaya,Lukashenko,Tsikhanouskaya,Cherechen,Against all,Number of ballots declared invalid,Number of ballots received by the precinct commission,Number of spoiled ballots,Number of unused ballots
1305,Минск,Центральный,Минск,"ул. Азизова, 3, государственное учреждение обр...",23,07-009-0023,1704.0,1195.0,1190,542.0,...,15.0,13,761,226,21.0,134.0,20.0,1789,1.0,593.0
1306,Минск,Центральный,Минск,"ул. Кропоткина, 97, общежитие № 2",28,07-009-0028,1158.0,765.0,765,332.0,...,36.0,32,491,120,8.0,59.0,19.0,1208,1.0,442.0
1307,Минск,Центральный,Минск,"ул. Куйбышева, 19, государственное учреждение ...",32,07-009-0032,1053.0,668.0,668,189.0,...,22.0,11,407,114,9.0,85.0,20.0,1106,1.0,437.0
1308,Минск,Центральный,Минск,"ул. М. Богдановича, 35, государственное учрежд...",34,07-009-0034,1358.0,971.0,971,381.0,...,37.0,32,627,166,22.0,87.0,NaN,NaN,NaN,NaN
1309,Минск,Центральный,Минск,"ул. Комсомольская, 21, государственное учрежде...",35,07-009-0035,1182.0,775.0,775,266.0,...,8.0,5,541,194,5.0,12.0,10.0,1241,3.0,463.0

In [4]:
df.shape

(1310, 22)

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1310 entries, 0 to 1309
Data columns (total 22 columns):
 #   Column                                                                Non-Null Count  Dtype
---  ------                                                                --------------  -----
 0   Region                                                                1310 non-null   str
 1   District                                                              1310 non-null   str
 2   City                                                                  1310 non-null   str
 3   Address                                                               1310 non-null   str
 4   Polling station number                                                1310 non-null   int64
 5   Polling station code                                                  1310 non-null   str
 6   Total number of voters                                                1304 non-null   float64
 7   Number of voters who received a ballot                                1300 non-null   float64
 8   Number of voters who took part in the vote                            1310 non-null   int64
 9   Number of voters who took part in early voting                        1300 non-null   float64
 10  Number of voters who took part in the vote at the place of residence  1295 non-null   float64
 11  Number of voters who took part in the vote on election day            1303 non-null   float64
 12  Dmitriev                                                              1308 non-null   float64
 13  Konopackaya                                                           1310 non-null   int64
 14  Lukashenko                                                            1310 non-null   int64
 15  Tsikhanouskaya                                                        1310 non-null   int64
 16  Cherechen                                                             1305 non-null   float64
 17  Against all                                                           1307 non-null   float64
 18  Number of ballots declared invalid                                    677 non-null    float64
 19  Number of ballots received by the precinct commission                 678 non-null    str
 20  Number of spoiled ballots                                             559 non-null    float64
 21  Number of unused ballots                                              676 non-null    float64
dtypes: float64(11), int64(5), str(6)
memory usage: 225.3 KB

In [6]:
df.describe()

,Polling station number,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,Number of voters who took part in the vote at the place of residence,Number of voters who took part in the vote on election day,Dmitriev,Konopackaya,Lukashenko,Tsikhanouskaya,Cherechen,Against all,Number of ballots declared invalid,Number of spoiled ballots,Number of unused ballots
count,1310.000000,1304.000000,1300.000000,1310.000000,1300.000000,1295.000000,1303.000000,1308.000000,1310.000000,1310.000000,1310.000000,1305.000000,1307.000000,677.000000,559.000000,676.000000
mean,39.825191,1785.555215,1439.295385,1432.059542,576.646923,46.265637,812.962394,24.139144,28.060305,883.810687,360.083206,23.088889,99.127008,27.069424,7.169946,460.698225
std,31.826124,622.735782,547.944479,544.855858,295.576712,64.509903,385.170032,16.511077,22.347253,444.747307,299.133940,17.537464,77.593499,32.972728,43.706189,280.393930
min,1.000000,37.000000,37.000000,37.000000,0.000000,0.000000,37.000000,0.000000,0.000000,13.000000,5.000000,0.000000,-48.000000,0.000000,0.000000,0.000000
25%,14.000000,1414.000000,1087.500000,1078.250000,354.000000,11.000000,542.000000,13.000000,13.000000,563.500000,139.000000,11.000000,45.000000,8.000000,1.000000,223.500000
50%,31.000000,1831.000000,1407.500000,1398.500000,560.000000,24.000000,776.000000,21.000000,21.000000,834.500000,252.000000,19.000000,85.000000,15.000000,2.000000,448.000000
75%,60.000000,2205.250000,1795.500000,1788.000000,756.250000,52.000000,1045.000000,31.000000,37.000000,1145.500000,509.000000,31.000000,131.000000,32.000000,4.000000,681.250000
max,144.000000,4225.000000,3928.000000,3924.000000,1799.000000,581.000000,2874.000000,132.000000,134.000000,2533.000000,2341.000000,140.000000,788.000000,402.000000,811.000000,1332.000000

In [7]:
df.describe(include="object")

C:\Users\Admin\AppData\Local\Temp\ipykernel_23728\702825166.py:1: Pandas4Warning: For backward compatibility, 'str' dtypes are included by select_dtypes when 'object' dtype is specified. This behavior is deprecated and will be removed in a future version. Explicitly pass 'str' to `include` to select them, or to `exclude` to remove them and silence this warning.
See https://pandas.pydata.org/docs/user_guide/migration-3-strings.html#string-migration-select-dtypes for details on how to write code that works with pandas 2 and 3.
  df.describe(include="object")

,Region,District,City,Address,Polling station code,Number of ballots received by the precinct commission
count,1310,1310,1310,1310,1310,678
unique,7,109,291,1095,1310,401
top,Минск,Минский,Минск,"ГУО “Средняя школа №38 г. Гродно”, г. Гродно, ...",01-010-0001,2000
freq,432,97,407,5,1,22

In [8]:
df.isnull().sum()

Region                                                                    0
District                                                                  0
City                                                                      0
Address                                                                   0
Polling station number                                                    0
Polling station code                                                      0
Total number of voters                                                    6
Number of voters who received a ballot                                   10
Number of voters who took part in the vote                                0
Number of voters who took part in early voting                           10
Number of voters who took part in the vote at the place of residence     15
Number of voters who took part in the vote on election day                7
Dmitriev                                                                  2
Konopackaya                                                               0
Lukashenko                                                                0
Tsikhanouskaya                                                            0
Cherechen                                                                 5
Against all                                                               3
Number of ballots declared invalid                                      633
Number of ballots received by the precinct commission                   632
Number of spoiled ballots                                               751
Number of unused ballots                                                634
dtype: int64

In [9]:
df.duplicated().sum()

np.int64(0)

In [10]:
df_clean = df.copy()

df_clean["Number of ballots received by the precinct commission"] = pd.to_numeric(
    df_clean["Number of ballots received by the precinct commission"],
    errors="coerce"
)

In [11]:
df_drop = df_clean.dropna(subset=[
    "Region",
    "Polling station code",
    "Total number of voters",
    "Number of voters who took part in the vote"
])

In [12]:
df_fill = df_clean.copy()

df_fill["Number of voters who took part in early voting"] = \
   df_fill["Number of voters who took part in early voting"].fillna(
        df_fill["Number of voters who took part in early voting"].median()
    )

df_fill["Number of spoiled ballots"] = \
    df_fill["Number of spoiled ballots"].fillna(0)

Медиана, потому что есть выбросы, 0, если отсутствие событися

In [13]:
df_fill["City"].mode()

0    Минск
Name: City, dtype: str

In [14]:
city_mode = df_fill["City"].mode()[0]
df_fill["City"] = df_fill["City"].fillna(city_mode)

In [15]:
num_cols = df_fill.select_dtypes(include=["int64", "float64"]).columns
num_cols

stats_df = pd.DataFrame({
    "min": df_fill[num_cols].min(),
    "max": df_fill[num_cols].max(),
    "mean": df_fill[num_cols].mean(),
    "median": df_fill[num_cols].median(),
    "mode": df_fill[num_cols].mode().iloc[0],
    "variance": df_fill[num_cols].var(),
    "skewness": df_fill[num_cols].skew(),
    "kurtosis": df_fill[num_cols].kurt()
})

stats_df

,min,max,mean,median,mode,variance,skewness,kurtosis
Polling station number,1.0,144.0,39.825191,31.0,1.0,1012.902192,0.870650,-0.104695
Total number of voters,37.0,4225.0,1785.555215,1831.0,1780.0,387799.854201,-0.297694,-0.005211
Number of voters who received a ballot,37.0,3928.0,1439.295385,1407.5,1339.0,300243.152096,0.179678,0.130399
Number of voters who took part in the vote,37.0,3924.0,1432.059542,1398.5,1487.0,296867.906307,0.156775,0.053819
Number of voters who took part in early voting,0.0,1799.0,576.519847,560.0,560.0,86700.271187,0.595957,0.462267
Number of voters who took part in the vote at the place of residence,0.0,581.0,46.265637,24.0,0.0,4161.527528,3.390806,15.553835
Number of voters who took part in the vote on election day,37.0,2874.0,812.962394,776.0,653.0,148355.953270,0.639360,0.688608
Dmitriev,0.0,132.0,24.139144,21.0,15.0,272.615666,1.672372,5.135055
Konopackaya,0.0,134.0,28.060305,21.0,14.0,499.399722,1.514986,2.446597
Lukashenko,13.0,2533.0,883.810687,834.5,521.0,197800.167342,0.595117,0.150662
Tsikhanouskaya,5.0,2341.0,360.083206,252.0,101.0,89481.113774,1.556055,3.449878
Cherechen,0.0,140.0,23.088889,19.0,11.0,307.562645,1.505828,3.238903
Against all,-48.0,788.0,99.127008,85.0,87.0,6020.751085,1.767928,6.617835
Number of ballots declared invalid,0.0,402.0,27.069424,15.0,13.0,1087.200794,3.736604,27.741968
Number of ballots received by the precinct commission,100.0,4125.0,1919.318047,1950.0,2000.0,381991.929807,-0.278789,0.079659
Number of spoiled ballots,0.0,811.0,3.059542,0.0,0.0,826.878041,21.120622,525.285408
Number of unused ballots,0.0,1332.0,460.698225,448.0,120.0,78620.756204,0.221545,-0.806201

In [16]:
quantiles = df_fill[num_cols].quantile([0.05, 0.25, 0.50, 0.75, 0.95])
quantiles

,Polling station number,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,Number of voters who took part in the vote at the place of residence,Number of voters who took part in the vote on election day,Dmitriev,Konopackaya,Lukashenko,Tsikhanouskaya,Cherechen,Against all,Number of ballots declared invalid,Number of ballots received by the precinct commission,Number of spoiled ballots,Number of unused ballots
0.05,3.00,636.15,517.95,517.45,141.35,2.0,238.1,4.0,4.0,254.45,57.0,3.0,9.0,2.0,859.75,0.0,36.75
0.25,14.00,1414.00,1087.50,1078.25,355.25,11.0,542.0,13.0,13.0,563.50,139.0,11.0,45.0,8.0,1538.75,0.0,223.50
0.50,31.00,1831.00,1407.50,1398.50,560.00,24.0,776.0,21.0,21.0,834.50,252.0,19.0,85.0,15.0,1950.00,0.0,448.00
0.75,60.00,2205.25,1795.50,1788.00,755.75,52.0,1045.0,31.0,37.0,1145.50,509.0,31.0,131.0,32.0,2329.25,1.0,681.25
0.95,102.55,2745.70,2383.00,2379.55,1123.00,172.9,1524.9,53.0,75.0,1714.55,967.7,59.8,241.0,96.2,2900.00,6.0,918.25

In [17]:
df_feat = df_fill.copy()

df_feat["turnout_rate"] = (
    df_feat["Number of voters who took part in the vote"] /
    df_feat["Total number of voters"]
)

df_feat["early_voting_share"] = (
    df_feat["Number of voters who took part in early voting"] /
    df_feat["Number of voters who took part in the vote"]
)

df_feat["lukashenko_share"] = (
    df_feat["Lukashenko"] /
    df_feat["Number of voters who took part in the vote"]
)

df_feat["tsikhanouskaya_share"] = (
    df_feat["Tsikhanouskaya"] /
    df_feat["Number of voters who took part in the vote"]
)

df_feat["invalid_share"] = (
    df_feat["Number of ballots declared invalid"] /
    df_feat["Number of voters who took part in the vote"]
)

df_feat

,Region,District,City,Address,Polling station number,Polling station code,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,...,Against all,Number of ballots declared invalid,Number of ballots received by the precinct commission,Number of spoiled ballots,Number of unused ballots,turnout_rate,early_voting_share,lukashenko_share,tsikhanouskaya_share,invalid_share
0,Брестская,Брест - Ленинский,Брест,"ул. Гоголя, 7, УО «Брестский государственный м...",1,01-010-0001,1656.0,1329.0,1319,252.0,...,96.0,5.0,1660.0,1.0,330.0,0.796498,0.191054,0.351782,0.531463,0.003791
1,Брестская,Брест - Ленинский,Брест,"ул. Героев обороны Брестской крепости, 78, УО ...",2,01-010-0002,2646.0,2249.0,2249,707.0,...,194.0,13.0,2670.0,0.0,421.0,0.849962,0.314362,0.441974,0.421521,0.005780
2,Брестская,Брест - Ленинский,Брест,"ул. Пригородная, 25, УО «Брестское государстве...",4,01-010-0004,1805.0,1717.0,1714,537.0,...,97.0,15.0,1880.0,0.0,163.0,0.949584,0.313302,0.656359,0.230455,0.008751
3,Брестская,Брест - Ленинский,Брест,"ул. Смирнова, 21, общежитие ОАО «Брестский мяс...",5,01-010-0005,2270.0,2122.0,2122,863.0,...,91.0,NaN,NaN,0.0,NaN,0.934802,0.406692,0.709708,0.194156,NaN
4,Брестская,Брест - Ленинский,Брест,"ул. Смирнова, 63, ГУО «Средняя школа № 5 г. Бр...",6,01-010-0006,2746.0,2383.0,2383,507.0,...,174.0,NaN,NaN,0.0,NaN,0.867808,0.212757,0.387327,0.485522,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1305,Минск,Центральный,Минск,"ул. Азизова, 3, государственное учреждение обр...",23,07-009-0023,1704.0,1195.0,1190,542.0,...,134.0,20.0,1789.0,1.0,593.0,0.698357,0.455462,0.639496,0.189916,0.016807
1306,Минск,Центральный,Минск,"ул. Кропоткина, 97, общежитие № 2",28,07-009-0028,1158.0,765.0,765,332.0,...,59.0,19.0,1208.0,1.0,442.0,0.660622,0.433987,0.641830,0.156863,0.024837
1307,Минск,Центральный,Минск,"ул. Куйбышева, 19, государственное учреждение ...",32,07-009-0032,1053.0,668.0,668,189.0,...,85.0,20.0,1106.0,1.0,437.0,0.634378,0.282934,0.609281,0.170659,0.029940
1308,Минск,Центральный,Минск,"ул. М. Богдановича, 35, государственное учрежд...",34,07-009-0034,1358.0,971.0,971,381.0,...,87.0,NaN,NaN,0.0,NaN,0.715022,0.392379,0.645726,0.170958,NaN
1309,Минск,Центральный,Минск,"ул. Комсомольская, 21, государственное учрежде...",35,07-009-0035,1182.0,775.0,775,266.0,...,12.0,10.0,1241.0,3.0,463.0,0.655668,0.343226,0.698065,0.250323,0.012903

In [18]:
df_feat["station_size_group"] = pd.cut(
    df_feat["Total number of voters"],
    bins=[0, 1000, 2000, 3000, np.inf],
    labels=["small", "medium", "large", "very_large"]
)

In [19]:
df_before = df_feat[["Region", "City", "station_size_group"]].head()

df_ohe = pd.get_dummies(
    df_feat,
    columns=["Region", "City", "station_size_group"],
    drop_first=True
)

df_after = df_ohe.head()

In [20]:
df_before
df_after

,District,Address,Polling station number,Polling station code,Total number of voters,Number of voters who received a ballot,Number of voters who took part in the vote,Number of voters who took part in early voting,Number of voters who took part in the vote at the place of residence,Number of voters who took part in the vote on election day,...,City_пос. Дружный,City_пос. Новоколосово,City_пос. Октябрьский,City_пос. Усяж,City_пос.Первомайский,City_р.п. Речица,City_р.п.Елизово,station_size_group_medium,station_size_group_large,station_size_group_very_large
0,Брест - Ленинский,"ул. Гоголя, 7, УО «Брестский государственный м...",1,01-010-0001,1656.0,1329.0,1319,252.0,4.0,1063.0,...,False,False,False,False,False,False,False,True,False,False
1,Брест - Ленинский,"ул. Героев обороны Брестской крепости, 78, УО ...",2,01-010-0002,2646.0,2249.0,2249,707.0,37.0,1505.0,...,False,False,False,False,False,False,False,False,True,False
2,Брест - Ленинский,"ул. Пригородная, 25, УО «Брестское государстве...",4,01-010-0004,1805.0,1717.0,1714,537.0,42.0,1135.0,...,False,False,False,False,False,False,False,True,False,False
3,Брест - Ленинский,"ул. Смирнова, 21, общежитие ОАО «Брестский мяс...",5,01-010-0005,2270.0,2122.0,2122,863.0,23.0,1236.0,...,False,False,False,False,False,False,False,False,True,False
4,Брест - Ленинский,"ул. Смирнова, 63, ГУО «Средняя школа № 5 г. Бр...",6,01-010-0006,2746.0,2383.0,2383,507.0,20.0,1856.0,...,False,False,False,False,False,False,False,False,True,False